# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme: minimal-mistakes-jekyll
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


# Site settings
locale                   : "en-US"
title                    : "Domain-Driven Design Heuristics"
title_separator          : "-"
subtitle                 : "Part of virtualDDD.com"
name                     : "Developed by Kenny Baas-Schwegler & Marco Heimeshoff"
description              : "Helpfull heuristics to use in your software design"
url                      : "https://dddheuristics.com"
baseurl                  : ""
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "/assets/img/kandinsky.jpg" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/vddd_logo_small.png"
masthead_title           : "DDD Heuristics"
#collections_dir: heuristics
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : "dddheuristics"

# Social Sharing
twitter:
  username               :

# Site Author
author:
  name             : "Virtual DDD"
  avatar           : "/assets/images/blank-avatar.png"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
timezone: Europe/Amsterdam # Timezone for blog posts and alike
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
permalink: pretty

# Set plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# 5. Collections
collections:
  guiding-heuristics:
    output: true
    permalink: /:collection/:path/
  design-heuristics:
    permalink: /:collection/:path/
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
      comments: true
      header:
        overlay_color: "#1a202c"
        overlay_filter: "0.65"
        overlay_image: /assets/images/kandinsky.jpg
  - scope:
      type: guiding-heuristics
    values:
      layout: heuristics
  - scope:
      type: design-heuristics
    values:
      layout: heuristics
