# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://dddheuristics.com'
baseurl: ''
title: 'Domain-Driven Design Heuristics'
description: 'Helpfull heuristics to use in your software design'
permalink: pretty
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Header nav
navigation_header:
  Home: /
  About: /about/
  Cognitive Heuristics: /heuristics/

# Footer nav
navigation_footer:
  Back to top: "#top"

# 5. Collections
collections:
  cognitive_heuristics:
    title: Cognitive Heuristics # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_image: "/assets/img/kandinsky.jpg"


